### ISSUE TITLE
Error Open Operation BuyAsync 'Value cannot be null. (Parameter 'source')'

### ISSUE THREAD

**Issue by jpr14** [JorgeBeserra/IqOptionApiDotNet#181]
var buyResult = await client.BuyAsync(requestId,BalanceType.Practice, ActivePair.EURUSD_op, (decimal)1.5, OrderDirection.Call, exp);

**'Value cannot be null. (Parameter 'source')'**

This exception was originally thrown at this call stack:
    System.Linq.ThrowHelper.ThrowArgumentNullException(System.Linq.ExceptionArgument)
    System.Linq.Enumerable.TryGetFirst<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>, out bool)
    System.Linq.Enumerable.FirstOrDefault<TSource>(System.Collections.Generic.IEnumerable<TSource>, System.Func<TSource, bool>)
    IqOptionApiDotNet.Ws.IqOptionWebSocketClient.BuyAsync(string, IqOptionApiDotNet.Models.BalanceType, IqOptionApiDotNet.Models.ActivePair, decimal, IqOptionApiDotNet.Models.OrderDirection, System.DateTimeOffset)
    IqOptionApiDotNet.IqOptionApiDotNetClient.BuyAsync(string, IqOptionApiDotNet.Models.BalanceType, IqOptionApiDotNet.Models.ActivePair, decimal, IqOptionApiDotNet.Models.OrderDirection, System.DateTimeOffset)
    WinFormsApp10.Form1.button1_Click(object, System.EventArgs) in Form1.cs

**Comment by gunegrini** [comment]
estou com o mesmo problema! alguma solução? 

Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at IqOptionApiDotNet.Ws.IqOptionWebSocketClient.BuyAsync(String requestId, BalanceType balanceType, ActivePair pair, Decimal size, OrderDirection direction, DateTimeOffset expiration)
   at IqOptionApiDotNet.IqOptionApiDotNetClient.BuyAsync(String requestId, BalanceType balanceType, ActivePair pair, Decimal size, OrderDirection direction, DateTimeOffset expiration)
